import { StyleSheet, Platform } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FEFBF8",
  },
  header: {
    paddingTop: Platform.select({ ios: 50, android: 40 }),
    paddingHorizontal: 20,
    paddingBottom: 20,
    backgroundColor: "#FEFBF8",
    borderBottomWidth: 0,
  },
  headerTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 20,
  },
  backButton: {
    padding: 8,
    borderRadius: 24,
    backgroundColor: "#FFF9F5",
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: "600",
    color: "#2D2D2D",
    flex: 1,
    textAlign: "center",
    letterSpacing: -0.5,
  },
  menuButton: {
    padding: 8,
    borderRadius: 24,
    backgroundColor: "#FFF9F5",
  },
  tabsContainer: {
    flexDirection: "row",
    backgroundColor: "#FFF9F5",
    borderRadius: 28,
    padding: 6,
    marginBottom: 16,
  },
  tab: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 24,
    alignItems: "center",
  },
  tabActive: {
    backgroundColor: "#FFE5E5",
  },
  tabText: {
    fontSize: 15,
    fontWeight: "500",
    color: "#B8B8B8",
    letterSpacing: -0.3,
  },
  tabTextActive: {
    color: "#FF8A9B",
    fontWeight: "600",
  },
  markAllButton: {
    backgroundColor: "#E8F5E9",
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 28,
    alignItems: "center",
  },
  markAllButtonText: {
    color: "#81C784",
    fontSize: 15,
    fontWeight: "600",
    letterSpacing: -0.3,
  },
  content: {
    flex: 1,
    backgroundColor: "#FEFBF8",
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#FEFBF8",
  },
  emptyContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#FEFBF8",
    paddingHorizontal: 32,
  },
  emptyText: {
    fontSize: 16,
    color: "#C8C8C8",
    marginTop: 16,
    textAlign: "center",
    letterSpacing: -0.3,
  },
  notificationsList: {
    paddingVertical: 12,
    paddingHorizontal: 20,
  },
  notificationItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: "#FFFFFF",
    borderRadius: 28,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  notificationLeft: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
    marginRight: 12,
  },
  avatarContainer: {
    position: "relative",
    marginRight: 14,
  },
  avatar: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: "#FFF9F5",
  },
  avatarPlaceholder: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: "#FFF9F5",
    alignItems: "center",
    justifyContent: "center",
  },
  iconOverlay: {
    position: "absolute",
    bottom: 0,
    right: 0,
    width: 22,
    height: 22,
    borderRadius: 11,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2.5,
    borderColor: "#FFFFFF",
  },
  notificationContent: {
    flex: 1,
  },
  notificationText: {
    fontSize: 15,
    color: "#2D2D2D",
    marginBottom: 6,
    lineHeight: 22,
    letterSpacing: -0.3,
  },
  notificationTime: {
    fontSize: 13,
    color: "#B8B8B8",
    letterSpacing: -0.2,
  },
  notificationRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  statusDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: "#FFB3BA",
  },
  notificationMenu: {
    padding: 6,
    borderRadius: 20,
    backgroundColor: "#FFF9F5",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.3)",
    justifyContent: "center",
    alignItems: "center",
  },
  menuContainer: {
    backgroundColor: "#FFFFFF",
    borderRadius: 32,
    paddingVertical: 12,
    minWidth: 220,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 16,
    elevation: 8,
  },
  headerMenuContainer: {
    backgroundColor: "#FFFFFF",
    borderRadius: 32,
    paddingVertical: 12,
    minWidth: 260,
    position: "absolute",
    top: Platform.select({ ios: 100, android: 80 }),
    right: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 16,
    elevation: 8,
  },
  menuItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 14,
    paddingHorizontal: 20,
    gap: 14,
  },
  menuItemDelete: {
    borderTopWidth: 1,
    borderTopColor: "#FFF9F5",
  },
  menuItemText: {
    fontSize: 16,
    color: "#2D2D2D",
    flex: 1,
    letterSpacing: -0.3,
  },
  menuItemTextDelete: {
    color: "#FF8A9B",
  },
  loadingMoreContainer: {
    paddingVertical: 20,
    alignItems: "center",
  },
});

export default styles;
