import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFF9F5",
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#FFF9F5",
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    color: "#7A8A99",
    fontWeight: "500",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: 50,
    paddingBottom: 16,
    backgroundColor: "#FFFFFF",
    borderBottomWidth: 1,
    borderBottomColor: "#F0F4F8",
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#F8F9FA",
    alignItems: "center",
    justifyContent: "center",
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: "600",
    color: "#2C3E50",
    flex: 1,
    textAlign: "center",
    letterSpacing: 0.3,
  },
  headerRight: {
    width: 40,
  },
  voucherCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 28,
    margin: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: "#E8EDF2",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
    position: "relative",
    overflow: "hidden",
  },
  voucherCardHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 24,
    gap: 16,
  },
  voucherIconContainer: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: "#FFF0F0",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#FFE5E5",
  },
  voucherHeaderInfo: {
    flex: 1,
  },
  voucherCode: {
    fontSize: 24,
    fontWeight: "700",
    color: "#F5B8C4",
    marginBottom: 8,
    letterSpacing: 0.2,
  },
  voucherName: {
    fontSize: 18,
    fontWeight: "600",
    color: "#2C3E50",
    lineHeight: 26,
    letterSpacing: 0.2,
  },
  voucherStatusBadge: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
    alignSelf: "flex-start",
  },
  voucherStatusText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#fff",
    textTransform: "uppercase",
  },
  voucherDetails: {
    gap: 24,
  },
  voucherDetailSection: {
    gap: 12,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: "#F0F4F8",
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#2C3E50",
    marginBottom: 8,
    letterSpacing: 0.2,
  },
  voucherDetailRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 12,
  },
  voucherDetailLabel: {
    fontSize: 15,
    color: "#7A8A99",
    fontWeight: "500",
    flex: 1,
  },
  voucherDetailValue: {
    fontSize: 15,
    color: "#2C3E50",
    fontWeight: "700",
    flex: 1,
    textAlign: "right",
  },
  voucherOutOfStock: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.3)",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 28,
  },
  voucherOutOfStockText: {
    fontSize: 20,
    fontWeight: "700",
    color: "#FFFFFF",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 60,
  },
  emptyTitle: {
    fontSize: 20,
    fontWeight: "600",
    color: "#2C3E50",
    marginTop: 16,
    marginBottom: 8,
    letterSpacing: 0.2,
  },
  bottomSpacing: {
    height: 100,
  },
  applicableTourButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    padding: 16,
    backgroundColor: "#F0F4F8",
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#B8D4E3",
  },
  applicableTourButtonText: {
    flex: 1,
    fontSize: 15,
    fontWeight: "600",
    color: "#5A6C7D",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.3)",
    justifyContent: "flex-end",
  },
  modalContent: {
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    maxHeight: "80%",
    paddingBottom: 20,
    shadowOpacity: 0.08,
    shadowRadius: 24,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#F0F4F8",
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "600",
    color: "#2C3E50",
    letterSpacing: 0.2,
  },
  modalCloseButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#F8F9FA",
    alignItems: "center",
    justifyContent: "center",
  },
  modalScrollView: {
    padding: 16,
  },
  tourLoadingContainer: {
    paddingVertical: 40,
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
  },
  tourLoadingText: {
    fontSize: 14,
    color: "#666",
  },
  tourItem: {
    backgroundColor: "#F8F9FA",
    borderRadius: 24,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#E8EDF2",
  },
  tourItemName: {
    fontSize: 16,
    fontWeight: "600",
    color: "#2C3E50",
    marginBottom: 8,
    letterSpacing: 0.2,
  },
  tourItemDescription: {
    fontSize: 14,
    color: "#7A8A99",
    marginBottom: 12,
    lineHeight: 20,
  },
  tourItemInfo: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  tourItemPrice: {
    fontSize: 16,
    fontWeight: "700",
    color: "#F5B8C4",
  },
  tourItemDuration: {
    fontSize: 14,
    color: "#7A8A99",
  },
  tourEmptyContainer: {
    paddingVertical: 40,
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
  },
  tourEmptyText: {
    fontSize: 14,
    color: "#666",
    textAlign: "center",
    paddingHorizontal: 16,
  },
});

export default styles;
