import { StyleSheet, Dimensions, Platform } from "react-native";
import { colors, spacing, borderRadius } from "../../constants/theme";

const { width } = Dimensions.get("window");

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f8f9fa",
    paddingTop: 8,
  },
  containerIos: {
    paddingTop: 16,
  },
  containerSm: {
    paddingTop: 24,
  },
  bottomSpacing: {
    height: Platform.select({ ios: 24, android: 80 }) as number,
  },
  topHeader: {
    paddingHorizontal: 16,
    paddingTop: 20,
    paddingBottom: 8,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#ffffff",
  },
  topHeaderSm: {
    paddingTop: 38,
  },
  welcomeLabel: {
    fontSize: 14,
    color: "#6c757d",
    fontWeight: "400",
    marginBottom: 2,
  },
  usernameContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  usernameText: {
    fontSize: 20,
    fontWeight: "700",
    color: "#212529",
    letterSpacing: -0.5,
  },
  premiumIconContainer: {
    padding: 4,
  },
  rightActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  languageContainer: {
    position: "relative",
  },
  langBadge: {
    backgroundColor: "#ffffff",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderWidth: 1,
    borderColor: "#e9ecef",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  flagImage: {
    width: 20,
    height: 15,
    borderRadius: 3,
  },
  langText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#212529",
  },
  dropdown: {
    position: "absolute",
    top: 50,
    right: 0,
    backgroundColor: "#ffffff",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#e9ecef",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
    zIndex: 1000,
    minWidth: 140,
  },
  dropdownItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 10,
  },
  dropdownItemActive: {
    backgroundColor: "#f8f9fa",
  },
  dropdownText: {
    fontSize: 14,
    color: "#212529",
    flex: 1,
    fontWeight: "500",
  },
  dropdownTextActive: {
    fontWeight: "600",
  },
  dropdownCode: {
    fontSize: 11,
    color: "#6c757d",
    fontWeight: "600",
  },
  dropdownCodeActive: {
    color: "#212529",
  },
  settingBtn: {
    padding: 8,
    borderRadius: 20,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#e9ecef",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  searchBox: {
    marginHorizontal: 16,
    marginTop: 12,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderRadius: 25,
    paddingHorizontal: 16,
    height: 48,
    borderWidth: 1,
    borderColor: "#e9ecef",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  searchPlaceholder: {
    marginLeft: 12,
    color: "#6c757d",
    fontSize: 16,
    fontWeight: "400",
  },
  header: {
    paddingTop: 50,
    paddingBottom: spacing.lg,
    paddingHorizontal: spacing.lg,
  },
  headerContent: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  logoContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  logo: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(255,255,255,0.2)",
    alignItems: "center",
    justifyContent: "center",
    marginRight: spacing.sm,
  },
  logoText: {
    color: "white",
    fontSize: 18,
    fontWeight: "bold",
  },
  appName: {
    color: "white",
    fontSize: 18,
    fontWeight: "600",
  },
  headerActions: {
    flexDirection: "row",
    gap: spacing.sm,
  },
  authButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: borderRadius.md,
    backgroundColor: "rgba(255,255,255,0.2)",
  },
  registerButton: {
    backgroundColor: "rgba(255,255,255,0.3)",
  },
  authButtonText: {
    color: "white",
    fontSize: 14,
    fontWeight: "600",
    marginLeft: spacing.xs,
  },

  section: {
    padding: spacing.md,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: spacing.md,
  },
  sectionTitle: {
    fontSize: 22,
    fontWeight: "bold",
    color: colors.text.primary,
  },
  sectionTitleSm: {
    fontSize: 20,
  },
  seeAllText: {
    fontSize: 16,
    color: colors.primary.main,
    fontWeight: "600",
  },
  toursContainer: {
    marginBottom: -12,
  },
  tourCard: {
    width: width * 0.56,
    backgroundColor: colors.surface.primary,
    borderRadius: borderRadius.lg,
    borderWidth: 1,
    borderColor: colors.border.medium,
    marginRight: spacing.md,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    overflow: "hidden",
  },
  imageContainer: {
    position: "relative",
    width: "100%",
    height: 168,
  },
  tourImage: {
    width: "100%",
    height: 168,
    borderTopLeftRadius: borderRadius.lg,
    borderTopRightRadius: borderRadius.lg,
  },
  imageLoadingOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(255, 255, 255, 0.8)",
    justifyContent: "center",
    alignItems: "center",
    borderTopLeftRadius: borderRadius.lg,
    borderTopRightRadius: borderRadius.lg,
  },
  noImageContainer: {
    width: "100%",
    height: 180,
    backgroundColor: "#f5f5f5",
    justifyContent: "center",
    alignItems: "center",
    borderTopLeftRadius: borderRadius.lg,
    borderTopRightRadius: borderRadius.lg,
  },
  noImageText: {
    color: "#999",
    fontSize: 12,
    marginTop: 8,
  },
  durationBadge: {
    position: "absolute",
    top: 10,
    left: 10,
    backgroundColor: colors.background.secondary,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  durationText: { fontSize: 10, fontWeight: "700", color: colors.text.primary },
  tourContent: {
    padding: spacing.md,
    flexGrow: 1,
    flexShrink: 0,
  },
  tourTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: colors.text.primary,
    marginBottom: spacing.xs,
  },
  tourTitleSm: {
    fontSize: 16,
  },
  tourLocation: {
    fontSize: 14,
    color: colors.text.secondary,
    marginBottom: spacing.sm,
    marginTop: 8,
  },
  tourPrice: {
    fontSize: 16,
    fontWeight: "bold",
    color: colors.primary.main,
  },
  tourMeta: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: spacing.sm,
  },
  tourRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: spacing.sm,
    marginTop: "auto",
  },
  locationContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  ratingContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  ratingText: {
    fontSize: 14,
    fontWeight: "600",
    color: colors.text.primary,
    marginLeft: spacing.xs,
  },
  tourDuration: {
    fontSize: 12,
    color: colors.text.secondary,
  },

  newsCard: {
    flexDirection: "row",
    backgroundColor: colors.surface.primary,
    borderRadius: borderRadius.md,
    padding: spacing.md,
    marginBottom: spacing.md,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
    alignItems: "center",
    gap: spacing.md,
  },
  avatarCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.background.secondary,
    alignItems: "center",
    justifyContent: "center",
  },
  newsImage: {
    width: 80,
    height: 80,
    borderRadius: borderRadius.sm,
    marginRight: spacing.md,
  },
  newsContent: {
    flex: 1,
    marginRight: 8,
  },
  hashtagsContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    marginTop: 4,
  },
  newsTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.text.primary,
    marginBottom: spacing.xs,
  },
  newsSummary: {
    fontSize: 14,
    color: colors.text.secondary,
    marginBottom: spacing.xs,
    lineHeight: 20,
  },
  newsDate: {
    fontSize: 12,
    color: colors.text.disabled,
  },
  tag: {
    fontSize: 12,
    color: colors.text.primary,
    backgroundColor: colors.background.secondary,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
  },
  articlesContainer: {
    marginBottom: -20,
  },
  articleCard: {
    width: width * 0.56,
    backgroundColor: colors.surface.primary,
    borderRadius: borderRadius.lg,
    borderWidth: 1,
    borderColor: colors.border.medium,
    marginRight: spacing.sm,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    overflow: "hidden",
  },
  articleImage: {
    width: "100%",
    height: 140,
    borderTopLeftRadius: borderRadius.lg,
    borderTopRightRadius: borderRadius.lg,
  },
  articleContent: {
    paddingVertical: 6,
    paddingHorizontal: 8,
  },
  articleTitle: {
    fontSize: 15,
    fontWeight: "bold",
    color: colors.text.primary,
    marginBottom: 6,
  },
  articleSummary: {
    fontSize: 12,
    color: colors.text.secondary,
    marginBottom: 6,
    lineHeight: 16,
  },
  articleMeta: {
    fontSize: 12,
    color: colors.text.disabled,
  },
  ctaSection: {
    padding: spacing.lg,
    marginBottom: 100,
  },
  ctaContainer: {
    borderRadius: borderRadius.lg,
    padding: spacing.xl,
    alignItems: "center",
  },
  ctaTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: "white",
    marginBottom: spacing.sm,
    textAlign: "center",
  },
  ctaSubtitle: {
    fontSize: 16,
    color: "rgba(255,255,255,0.9)",
    marginBottom: spacing.lg,
    textAlign: "center",
  },
  ctaButton: {
    backgroundColor: "white",
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.md,
    borderRadius: borderRadius.md,
  },
  ctaButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.primary.main,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 40,
  },
  loadingText: {
    marginTop: 8,
    fontSize: 14,
    color: "#666",
  },
  emptyContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 40,
  },
  emptyText: {
    fontSize: 14,
    color: "#666",
  },
  priceContainer: {
    flexDirection: "row",
    alignItems: "baseline",
    marginTop: 8,
    marginBottom: 0,
  },
  priceText: {
    fontSize: 16,
    fontWeight: "bold",
    color: colors.primary.main,
  },
  priceTextSm: {
    fontSize: 14,
  },

  // Language-specific tweaks
  langKoAdjust: {
    letterSpacing: 0,
    lineHeight: 20,
  },
  langViAdjust: {
    letterSpacing: 0.1,
  },
  priceUnit: {
    fontSize: 12,
    color: colors.text.secondary,
    marginLeft: 4,
  },
});

export default styles;
