import { StyleSheet } from "react-native";
import { typography } from "../../src/constants/theme";

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#f8f9fa" },
  imageWrapper: {
    position: "relative",
    margin: 12,
    marginTop: 30,
    borderRadius: 16,
    overflow: "hidden",
  },
  heroImage: { width: "100%", height: 260, borderRadius: 16 },
  backBtn: { position: "absolute", top: 12, left: 12 },
  backCircle: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
  imageOverlay: {
    position: "absolute",
    left: 16,
    right: 16,
    bottom: 16,
  },
  overlayTitle: {
    fontSize: typography.h5.fontSize,
    fontWeight: "600",
    color: "#fff",
    textShadowColor: "rgba(0,0,0,0.35)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  overlayRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 6,
  },
  overlayLocation: { fontSize: typography.body2.fontSize, color: "#fff" },
  content: { paddingHorizontal: 16, paddingBottom: 24 },
  metaBox: {
    borderTopWidth: 2,
    borderBottomWidth: 2,
    borderColor: "#eee",
    paddingVertical: 12,
    marginBottom: 24,
  },
  metaRowContent: {
    flexDirection: "row",
    alignItems: "stretch",
    justifyContent: "space-between",
    paddingHorizontal: 8,
  },
  metaCol: { flex: 1, paddingHorizontal: 8, alignItems: "center" },
  metaDivider: { width: 2, backgroundColor: "#e0e0e0", alignSelf: "stretch" },
  metaLabelCaps: {
    fontSize: typography.body2.fontSize,
    color: "#6c757d",
    letterSpacing: 1,
    marginBottom: 6,
    fontWeight: "700",
    textAlign: "center",
  },
  metaValueRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  metaValue: {
    fontSize: 16,
    fontWeight: "800",
    color: "#111",
    textAlign: "center",
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#111",
    marginBottom: 16,
  },
  paragraph: { fontSize: 13, lineHeight: 18, color: "#555", marginBottom: 24 },
  card: {
    backgroundColor: "#fff",
    borderRadius: 24,
    paddingVertical: 24,
    paddingHorizontal: 16,
    borderWidth: 2,
    borderColor: "#cfcfcf",
    marginBottom: 24,
  },
  infoGrid: {
    flexDirection: "row",
    alignItems: "stretch",
    justifyContent: "space-between",
  },
  infoCol: { flex: 1, alignItems: "center" },
  infoDivider: {
    width: 2,
    backgroundColor: "#cfcfcf",
    borderRadius: 1,
    marginHorizontal: 6,
  },
  infoLabel: {
    fontSize: typography.caption.fontSize,
    color: "#9e9e9e",
    letterSpacing: 1,
    marginBottom: 12,
    fontWeight: "700",
    textAlign: "center",
  },
  infoValue: {
    fontSize: 15,
    lineHeight: 24,
    color: "#111",
    fontWeight: "800",
    textAlign: "center",
  },
  sectionBlock: {
    marginTop: 36,
    marginBottom: 24,
    paddingHorizontal: 8,
    position: "relative",
  },
  blockHeader: {
    position: "absolute",
    top: -22,
    left: 7,
    right: 7,
    height: 44,
    backgroundColor: "#b9ffcc",
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "#b0e8c0",
    alignItems: "center",
    justifyContent: "center",
  },
  blockHeaderText: { fontSize: 16, fontWeight: "700", color: "#111" },
  blockBox: {
    height: 260,
    backgroundColor: "#fff",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#d9d9d9",
  },
  bottomSpace: { height: 140 },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#f8f9fa",
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    color: "#666",
  },
  errorContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#f8f9fa",
    padding: 20,
  },
  errorTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#333",
    marginTop: 16,
    textAlign: "center",
  },
  retryButton: {
    marginTop: 20,
    backgroundColor: "#007AFF",
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 8,
  },
  retryButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
  },
  contentBlock: {
    marginBottom: 16,
  },
  contentBox: {
    height: 200,
    backgroundColor: "#fff",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#d9d9d9",
    marginBottom: 12,
  },
  contentHeader: {
    paddingHorizontal: 4,
  },
  contentTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#111",
    marginBottom: 8,
  },
  contentDescription: {
    fontSize: 14,
    color: "#666",
    lineHeight: 20,
  },
});

export default styles;
