import { StyleSheet, Dimensions } from "react-native";
import { typography } from "../../../constants/theme";

const { width, height } = Dimensions.get("window");
const isSmallScreen = width <= 360 || height <= 700;

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#f8f9fa" },
  imageWrapper: {
    position: "relative",
    margin: 10,
    marginTop: 30,
    borderRadius: 16,
    overflow: "hidden",
  },
  heroImage: { width: "100%", height: 260, borderRadius: 16 },
  backBtn: { position: "absolute", top: 12, left: 12 },
  backCircle: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
  imageOverlay: {
    position: "absolute",
    left: 16,
    right: 16,
    bottom: 16,
  },
  overlayTitle: {
    fontSize: typography.h5.fontSize,
    fontWeight: "600",
    color: "#fff",
    textShadowColor: "rgba(0,0,0,0.35)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  overlayRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 4,
  },
  overlayLocation: { fontSize: typography.body2.fontSize, color: "#fff" },
  content: { paddingHorizontal: 12, paddingBottom: 20 },
  metaBox: {
    borderTopWidth: 2,
    borderBottomWidth: 2,
    borderColor: "#eee",
    paddingVertical: 8,
    marginBottom: 20,
  },
  metaRowContent: {
    flexDirection: "row",
    alignItems: "stretch",
    justifyContent: "space-between",
    paddingHorizontal: 2,
  },
  metaCol: { flex: 1, paddingHorizontal: 2, alignItems: "center" },
  metaColNarrow: { flexGrow: 0, flexShrink: 1, flexBasis: "20%" },
  metaColWide: { flexGrow: 0, flexShrink: 1, flexBasis: "30%" },
  metaColStart: { alignItems: "flex-start", paddingLeft: 0 },
  metaDivider: {
    width: StyleSheet.hairlineWidth,
    backgroundColor: "#e0e0e0",
    alignSelf: "stretch",
  },
  metaLabelCaps: {
    fontSize: typography.body2.fontSize,
    color: "#6c757d",
    letterSpacing: 1,
    marginBottom: 6,
    fontWeight: "700",
    textAlign: "center",
    flexShrink: 1,
  },
  metaLabelCapsSm: {
    fontSize: 10.5,
    letterSpacing: 0.2,
  },
  metaValueRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  metaValue: {
    fontSize: 16,
    fontWeight: "800",
    color: "#111",
    textAlign: "center",
  },
  metaValueSm: {
    fontSize: 14,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#111",
    marginBottom: 12,
  },
  sectionTitleSm: { fontSize: 14 },
  paragraph: { fontSize: 13, lineHeight: 18, color: "#555", marginBottom: 20 },
  card: {
    backgroundColor: "#fff",
    borderRadius: 24,
    paddingVertical: 20,
    paddingHorizontal: 12,
    borderWidth: 2,
    borderColor: "#cfcfcf",
    marginBottom: 20,
  },
  infoGrid: {
    flexDirection: "row",
    alignItems: "stretch",
    justifyContent: "space-between",
  },
  infoCol: { flex: 1, alignItems: "center", minWidth: 0 },
  infoDivider: {
    width: 2,
    backgroundColor: "#cfcfcf",
    borderRadius: 1,
    marginHorizontal: 4,
  },
  infoLabel: {
    fontSize: typography.caption.fontSize,
    color: "#9e9e9e",
    letterSpacing: 1,
    marginBottom: 12,
    fontWeight: "700",
    textAlign: "center",
  },
  infoLabelSm: { fontSize: 10, letterSpacing: 0.5 },
  infoValue: {
    fontSize: 15,
    lineHeight: 24,
    color: "#111",
    fontWeight: "800",
    textAlign: "center",
    includeFontPadding: false,
  },
  infoValueSm: { fontSize: 13 },
  sectionBlock: {
    marginTop: 36,
    marginBottom: 24,
    paddingHorizontal: 8,
    position: "relative",
  },
  outerCard: {
    position: "relative",
    backgroundColor: "#fff",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#d9d9d9",
    paddingTop: 20,
    paddingHorizontal: 12,
    paddingBottom: 12,
    marginBottom: 12,
    overflow: "visible",
  },
  blockHeader: {
    position: "absolute",
    top: -22,
    left: 12,
    right: 12,
    height: 44,
    backgroundColor: "#b9ffcc",
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "#b0e8c0",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2,
  },
  blockHeaderText: { fontSize: 16, fontWeight: "700", color: "#111" },
  blockBox: {
    paddingTop: 0,
    backgroundColor: "transparent",
    borderWidth: 0,
  },
  contentCard: {
    backgroundColor: "transparent",
    borderRadius: 12,
    padding: 4,
    marginBottom: 4,
  },
  voucherRow: {
    backgroundColor: "#fff",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    padding: 16,
    marginBottom: 20,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 5,
  },
  voucherRowContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  voucherRowLeft: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  voucherRowTextContainer: {
    marginLeft: 12,
    flex: 1,
  },
  voucherRowTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#111",
    marginBottom: 4,
  },
  voucherRowSubtitle: {
    fontSize: 14,
    color: "#666",
  },
  // Modal Styles
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
  },
  modalContent: {
    backgroundColor: "#fff",
    borderRadius: 20,
    maxHeight: "75%",
    width: "100%",
    maxWidth: 400,
    paddingBottom: 20,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 10,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#e5e7eb",
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#111",
  },
  modalCloseButton: {
    padding: 4,
    color: "#28a745",
  },
  modalScrollView: {
    paddingHorizontal: 16,
    paddingTop: 12,
  },
  voucherOptionCard: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.08,
    shadowRadius: 2,
    elevation: 3,
  },
  voucherOptionContent: {
    marginBottom: 10,
  },
  voucherOptionLeft: {
    flexDirection: "row",
    alignItems: "center",
  },
  voucherOptionIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#FFF5F5",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
  },
  voucherOptionInfo: {
    flex: 1,
  },
  voucherOptionCode: {
    fontSize: 15,
    fontWeight: "700",
    color: "#FF6B6B",
    marginBottom: 3,
  },
  voucherOptionName: {
    fontSize: 13,
    color: "#666",
    fontWeight: "500",
  },
  voucherOptionDetails: {
    gap: 5,
    paddingLeft: 46,
  },
  voucherOptionDetailRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  voucherOptionDetailLabel: {
    fontSize: 13,
    color: "#666",
    fontWeight: "500",
  },
  voucherOptionDetailValue: {
    fontSize: 13,
    color: "#FF6B6B",
    fontWeight: "700",
  },
  voucherLoadingContainer: {
    paddingVertical: 24,
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  voucherLoadingText: {
    fontSize: 14,
    color: "#666",
  },
  voucherEmptyContainer: {
    paddingVertical: 32,
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  voucherEmptyText: {
    fontSize: 14,
    color: "#999",
    textAlign: "center",
    paddingHorizontal: 16,
  },
  voucherErrorText: {
    fontSize: 14,
    color: "#d9534f",
    textAlign: "center",
    paddingHorizontal: 16,
  },
  modalFooter: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 16,
    borderTopWidth: 1,
    borderTopColor: "#e5e7eb",
  },
  modalCloseButtonFull: {
    paddingVertical: 12,
    borderRadius: 10,
    backgroundColor: "#28a745",
    alignItems: "center",
    justifyContent: "center",
  },
  modalCloseButtonText: {
    fontSize: 16,
    fontWeight: "700",
    color: "#fff",
  },
  bottomSpace: { height: 140 },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#f8f9fa",
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    color: "#666",
  },
  errorContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#f8f9fa",
    padding: 20,
  },
  errorTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#333",
    marginTop: 16,
    textAlign: "center",
  },
  retryButton: {
    marginTop: 20,
    backgroundColor: "#007AFF",
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 8,
  },
  retryButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
  },
  contentBlock: {
    marginBottom: 16,
  },
  contentBox: {
    height: 200,
    backgroundColor: "#fff",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#d9d9d9",
    marginBottom: 12,
  },
  contentHeader: {
    paddingHorizontal: 4,
  },
  contentTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#111",
    marginBottom: 8,
  },
  contentTitleSm: { fontSize: 16 },
  contentDescription: {
    fontSize: 14,
    color: "#666",
    lineHeight: 20,
  },
  contentDescriptionSm: { fontSize: 13, lineHeight: 18 },
});

export default styles;
