import { StyleSheet, Platform } from "react-native";
import { typography } from "../../../constants/theme";

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#f8f9fa" },
  imageWrapper: {
    position: "relative",
    margin: 12,
    marginTop: 30,
    borderRadius: 16,
    overflow: "hidden",
  },
  heroImage: { width: "100%", height: 260, borderRadius: 16 },
  backBtn: { position: "absolute", top: 12, left: 12 },
  backCircle: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
  imageOverlay: { position: "absolute", left: 16, right: 16, bottom: 16 },
  overlayTitle: {
    fontSize: typography.h5.fontSize,
    fontWeight: "600",
    color: "#fff",
  },
  overlayRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 6,
  },
  overlayLocation: { fontSize: typography.body2.fontSize, color: "#fff" },
  content: { paddingHorizontal: 12, paddingBottom: 20 },

  metaBox: {
    borderTopWidth: 2,
    borderBottomWidth: 2,
    borderColor: "#eee",
    paddingVertical: 8,
    marginBottom: 20,
  },
  metaRowContent: {
    flexDirection: "row",
    alignItems: "stretch",
    justifyContent: "space-between",
    paddingHorizontal: 2,
  },
  metaCol: { flex: 1, paddingHorizontal: 2, alignItems: "center", minWidth: 0 },
  metaDivider: {
    width: StyleSheet.hairlineWidth,
    backgroundColor: "#e0e0e0",
    alignSelf: "stretch",
  },
  metaLabelCaps: {
    fontSize: typography.body2.fontSize,
    color: "#6c757d",
    letterSpacing: 1,
    marginBottom: 6,
    fontWeight: "700",
    textAlign: "center",
    flexShrink: 1,
  },
  metaValueRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  metaValue: {
    fontSize: 16,
    fontWeight: "800",
    color: "#111",
    textAlign: "center",
  },

  sectionTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#111",
    marginBottom: 16,
  },
  paragraph: { fontSize: 13, lineHeight: 18, color: "#555", marginBottom: 24 },

  formTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#111",
    textAlign: "center",
    marginBottom: 12,
  },
  toggleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 16,
  },
  radioOuter: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 1.5,
    borderColor: "#111",
    alignItems: "center",
    justifyContent: "center",
  },
  radioChecked: {
    backgroundColor: "#2F9E44",
    borderColor: "#2F9E44",
  },
  toggleText: { fontSize: 14, color: "#111", fontWeight: "600" },
  inputReadonly: {
    backgroundColor: "#f5f5f5",
    color: "#666",
  },
  updateHint: {
    fontSize: 12,
    color: "#FF6B6B",
    marginTop: 4,
    fontStyle: "italic",
  },

  fieldGroup: { marginBottom: 14 },
  label: { fontSize: 14, color: "#111", marginBottom: 8, fontWeight: "600" },
  input: {
    height: 36,
    backgroundColor: "#fff",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#dadada",
    paddingHorizontal: 16,
    fontSize: 14,
  },
  noteInput: { height: 140, textAlignVertical: "top", borderRadius: 16 },
  sectionSubLabel: { fontSize: 14, color: "#111", marginBottom: 8 },
  dateRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 12,
    marginLeft: -6,
  },
  dateCol: { flex: 1, alignItems: "center" },
  datePill: {
    width: "68%",
    height: 34,
    borderRadius: 17,
    borderWidth: 1.5,
    borderColor: "#111",
    alignItems: "flex-end",
    justifyContent: "center",
  },
  caretCircle: {
    width: 34,
    height: 34,
    borderRadius: 17,
    borderWidth: 1.5,
    borderColor: "#111",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fff",
  },
  caretCircleRight: { marginRight: -10 },
  caretInner: { fontWeight: "800", fontSize: 18 },
  counterRowWrapper: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 16,
    gap: 12,
  },
  counterGroup: { alignItems: "center", flex: 1 },
  counterLabel: { fontSize: 18, fontWeight: "800", marginVertical: 6 },
  counterRow: { flexDirection: "row", alignItems: "center", gap: 12 },
  counterBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    borderWidth: 1.5,
    borderColor: "#111",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fff",
  },
  counterBtnLeft: { marginLeft: -10 },
  counterBtnRight: { marginRight: -10 },
  counterBtnText: { fontSize: 18, fontWeight: "700" },
  counterValue: {
    width: 28,
    textAlign: "center",
    fontSize: 16,
    fontWeight: "700",
  },

  counterHint: { fontSize: 11, color: "#6c757d", marginTop: 6 },
  counterPill: { position: "relative", width: "100%", paddingVertical: 12 },
  counterPillBox: {
    position: "relative",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "70%",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "#111",
    borderRadius: 20,
    height: 34,
  },
  pillLineTop: {
    position: "absolute",
    left: 48,
    right: 48,
    top: 0,
    height: 1,
    backgroundColor: "#111",
    borderRadius: 2,
  },
  pillLineBottom: {
    position: "absolute",
    left: 48,
    right: 48,
    bottom: 0,
    height: 1,
    backgroundColor: "#111",
    borderRadius: 2,
  },
  counterCenterValue: {
    fontSize: 18,
    fontWeight: "800",
    color: "#111",
    width: 28,
    textAlign: "center",
  },
  guestCard: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#ececec",
  },
  guestCardTitle: {
    fontSize: 16,
    fontWeight: "800",
    marginBottom: 8,
  },
  guestRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    marginBottom: 8,
  },
  guestForm: {
    marginBottom: 24,
    padding: 16,
    backgroundColor: "#f8f9fa",
    borderRadius: 12,
  },
  guestFieldGroup: {
    marginBottom: 20,
  },
  guestLabel: {
    fontSize: 14,
    fontWeight: "500",
    color: "#374151",
    marginBottom: 8,
  },
  genderRow: {
    position: "relative",
  },
  genderInput: {
    width: "100%",
    height: 36,
    borderRadius: 18,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#dadada",
    paddingHorizontal: 12,
    paddingRight: 32,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    position: "relative",
  },
  genderText: {
    fontSize: 14,
    color: "#111",
    fontWeight: "500",
    flex: 1,
    textAlign: "center",
    textAlignVertical: "center",
    lineHeight: 36,
  },
  nationalityRow: {
    position: "relative",
  },
  nationalityInput: {
    width: "100%",
    height: 36,
    borderRadius: 18,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#dadada",
    paddingHorizontal: 12,
    paddingRight: 32,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    position: "relative",
  },
  nationalityText: {
    fontSize: 14,
    color: "#111",
    fontWeight: "500",
    flex: 1,
    textAlign: "center",
    textAlignVertical: "center",
    lineHeight: 36,
  },
  dropdownIcon: {
    position: "absolute",
    right: 8,
    top: "50%",
    transform: [{ translateY: -8 }],
  },
  dropdownContainer: {
    position: "absolute",
    top: 41,
    left: 0,
    right: 0,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#dadada",
    borderRadius: 18,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    zIndex: 1000,
  },
  dropdownItem: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "#f3f4f6",
  },
  dropdownText: {
    fontSize: 14,
    color: "#374151",
    fontWeight: "400",
  },
  rowContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 16,
  },
  halfFieldGroup: {
    flex: 1,
  },
  fullNameFieldGroup: {
    flex: Platform.OS === "ios" ? 1.8 : 2,
  },
  dobFieldGroup: {
    flex: Platform.OS === "ios" ? 1.2 : 1,
  },
  halfInput: {
    width: "100%",
    height: 36,
    borderRadius: 18,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#dadada",
    paddingHorizontal: 12,
    fontSize: 14,
    color: "#111",
    fontWeight: "500",
  },
  guestIndex: {
    width: 20,
    textAlign: "center",
    fontWeight: "700",
    color: "#555",
    textAlignVertical: "center",
    lineHeight: 40,
  },
  spacer: { width: 8 },
  guestInput: {
    flex: 1,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#dadada",
    paddingHorizontal: 12,
    marginRight: 8,
    minWidth: 0,
    fontSize: 14,
    fontWeight: "500",
    textAlign: "left",
  },
  dobInput: {
    width: "100%",
    minWidth: 0,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#dadada",
    paddingHorizontal: 16,
    flexShrink: 1,
    justifyContent: "center",
  },
  dobText: {
    fontSize: 14,
    color: "#111",
    fontWeight: "600",
    letterSpacing: 0.2,
    includeFontPadding: false,
    textAlignVertical: "center",
    width: "100%",
    textAlign: "center",
    lineHeight: 36,
  },
  iosDateOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  iosDateCard: {
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 28,
    width: "100%",
    maxWidth: 420,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 16,
    elevation: 10,
    alignItems: "center",
  },
  iosDateTitle: {
    fontSize: 22,
    fontWeight: "700",
    color: "#212529",
    marginBottom: 16,
    textAlign: "center",
    letterSpacing: 0.3,
  },
  iosDateSelected: {
    fontSize: 32,
    fontWeight: "700",
    color: "#007AFF",
    marginBottom: 24,
    textAlign: "center",
    letterSpacing: 0.5,
  },
  iosDatePickerContainer: {
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 8,
  },
  iosDatePicker: {
    width: "100%",
    alignSelf: "center",
  },
  iosDateActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 12,
    marginTop: 20,
    width: "100%",
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.4)",
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
  },
  modalCard: {
    width: "100%",
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 16,
  },
  modalTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#111",
    marginBottom: 8,
  },
  quickRow: { flexDirection: "row", justifyContent: "space-between" },
  quickBtn: {
    flex: 1,
    marginHorizontal: 4,
    backgroundColor: "#f3f4f6",
    borderRadius: 8,
    paddingVertical: 10,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#e5e7eb",
  },
  quickText: { color: "#111", fontWeight: "600" },
  modalActions: { flexDirection: "row", justifyContent: "flex-end", gap: 8 },
  modalButton: {
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 8,
  },
  modalButtonText: { fontWeight: "700" },

  // Total Section Styles
  totalSection: {
    marginTop: 20,
    marginBottom: 16,
  },
  totalTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: "#111",
    textAlign: "center",
    marginBottom: 16,
  },
  totalBreakdown: {
    marginBottom: 16,
  },
  totalRow: {
    flexDirection: "row",
    justifyContent: "spaceBetween" as any,
    alignItems: "center",
    marginBottom: 8,
    marginLeft: "70%",
  },
  totalLabel: {
    fontSize: 16,
    color: "#666",
    fontWeight: "600",
    width: 60,
    textAlign: "left",
  },
  totalCount: {
    fontSize: 16,
    color: "#666",
    fontWeight: "600",
    marginLeft: 8,
  },
  totalPrice: {
    fontSize: 24,
    fontWeight: "800",
    color: "#111",
    textAlign: "right",
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#f8f9fa",
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    color: "#666",
  },
  errorContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#f8f9fa",
    padding: 20,
  },
  errorTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#333",
    marginTop: 16,
    textAlign: "center",
  },
  retryButton: {
    marginTop: 20,
    backgroundColor: "#007AFF",
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 8,
  },
  retryButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
  },
});

export default styles;
