import { Platform, StyleSheet } from "react-native";
import { typography } from "../../../constants/theme";

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#f8f9fa" },
  imageWrapper: {
    position: "relative",
    margin: 12,
    marginTop: 30,
    borderRadius: 16,
    overflow: "hidden",
  },
  heroImage: { width: "100%", height: 260, borderRadius: 16 },
  backBtn: { position: "absolute", top: 12, left: 12 },
  backCircle: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
  imageOverlay: { position: "absolute", left: 16, right: 16, bottom: 16 },
  overlayTitle: {
    fontSize: typography.h5.fontSize,
    fontWeight: "600",
    color: "#fff",
  },
  overlayRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 6,
  },
  overlayLocation: { fontSize: typography.body2.fontSize, color: "#fff" },
  content: { paddingHorizontal: 12, paddingBottom: 20 },

  metaBox: {
    borderTopWidth: 2,
    borderBottomWidth: 2,
    borderColor: "#eee",
    paddingVertical: 8,
    marginBottom: 20,
  },
  metaRowContent: {
    flexDirection: "row",
    alignItems: "stretch",
    justifyContent: "space-between",
    paddingHorizontal: 2,
  },
  metaCol: { flex: 1, paddingHorizontal: 2, alignItems: "center", minWidth: 0 },
  metaDivider: {
    width: StyleSheet.hairlineWidth,
    backgroundColor: "#e0e0e0",
    alignSelf: "stretch",
  },
  metaLabelCaps: {
    fontSize: typography.body2.fontSize,
    color: "#6c757d",
    letterSpacing: 1,
    marginBottom: 6,
    fontWeight: "700",
    textAlign: "center",
    flexShrink: 1,
  },
  metaValueRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  metaValue: {
    fontSize: 16,
    fontWeight: "800",
    color: "#111",
    textAlign: "center",
  },
  section: {
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#111",
    marginBottom: 16,
  },
  paragraph: { fontSize: 13, lineHeight: 18, color: "#555", marginBottom: 24 },

  formTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#111",
    textAlign: "center",
    marginBottom: 12,
  },
  toggleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 16,
  },
  toggleHint: {
    fontSize: 12,
    color: "#6c757d",
    marginTop: -8,
    marginBottom: 12,
    lineHeight: 16,
  },
  radioOuter: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 1.5,
    borderColor: "#111",
    alignItems: "center",
    justifyContent: "center",
  },
  radioChecked: {
    backgroundColor: "#2F9E44",
    borderColor: "#2F9E44",
  },
  toggleText: { fontSize: 14, color: "#111", fontWeight: "600" },
  inputReadonly: {
    backgroundColor: "#f5f5f5",
    color: "#666",
  },
  fieldGroup: { marginBottom: 14 },
  label: { fontSize: 14, color: "#111", marginBottom: 8, fontWeight: "600" },
  input: {
    minHeight: 40,
    height: 40,
    backgroundColor: "#fff",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#dadada",
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontSize: 14,
    includeFontPadding: false,
    textAlignVertical: "center",
  },
  noteInput: { height: 140, textAlignVertical: "top", borderRadius: 16 },
  sectionSubLabel: { fontSize: 14, color: "#111", marginBottom: 8 },
  totalGuestsHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
    marginTop: 10,
    marginBottom: 8,
  },
  dateRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 12,
    marginLeft: -6,
  },
  dateCol: { flex: 1, alignItems: "center" },
  datePill: {
    width: "68%",
    height: 34,
    borderRadius: 17,
    borderWidth: 1.5,
    borderColor: "#111",
    alignItems: "flex-end",
    justifyContent: "center",
  },
  caretCircle: {
    width: 34,
    height: 34,
    borderRadius: 17,
    borderWidth: 1.5,
    borderColor: "#111",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fff",
  },
  caretCircleRight: { marginRight: -10 },
  caretInner: { fontWeight: "800", fontSize: 18 },
  counterRowWrapper: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 16,
    gap: 12,
  },
  counterGroup: { alignItems: "center", flex: 1 },
  counterLabel: { fontSize: 18, fontWeight: "800", marginVertical: 6 },
  counterRow: { flexDirection: "row", alignItems: "center", gap: 12 },
  counterBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    borderWidth: 1.5,
    borderColor: "#111",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fff",
  },
  counterBtnLeft: { marginLeft: -10 },
  counterBtnRight: { marginRight: -10 },
  counterBtnText: { fontSize: 18, fontWeight: "700" },
  counterValue: {
    width: 28,
    textAlign: "center",
    fontSize: 16,
    fontWeight: "700",
  },

  counterHint: { fontSize: 11, color: "#6c757d", marginTop: 6 },
  counterPill: { position: "relative", width: "100%", paddingVertical: 12 },
  counterPillBox: {
    position: "relative",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "70%",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "#111",
    borderRadius: 20,
    height: 34,
  },
  pillLineTop: {
    position: "absolute",
    left: 48,
    right: 48,
    top: 0,
    height: 1,
    backgroundColor: "#111",
    borderRadius: 2,
  },
  pillLineBottom: {
    position: "absolute",
    left: 48,
    right: 48,
    bottom: 0,
    height: 1,
    backgroundColor: "#111",
    borderRadius: 2,
  },
  counterCenterValue: {
    fontSize: 18,
    fontWeight: "800",
    color: "#111",
    width: 28,
    textAlign: "center",
  },
  guestCard: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#ececec",
  },
  guestCardTitle: {
    fontSize: 16,
    fontWeight: "800",
    marginBottom: 8,
  },
  guestRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    marginBottom: 8,
  },
  guestForm: {
    marginBottom: 24,
    padding: 16,
    backgroundColor: "#f8f9fa",
    borderRadius: 12,
  },
  guestFieldGroup: {
    marginBottom: 20,
  },
  guestLabel: {
    fontSize: 14,
    fontWeight: "500",
    color: "#374151",
    marginBottom: 8,
  },
  genderRow: {
    position: "relative",
  },
  genderInput: {
    width: "100%",
    minHeight: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#dadada",
    paddingHorizontal: 12,
    paddingRight: 32,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  genderText: {
    fontSize: 14,
    color: "#111",
    fontWeight: "500",
    flex: 1,
    textAlign: "center",
    textAlignVertical: "center",
    includeFontPadding: false,
  },
  nationalityRow: {
    position: "relative",
  },
  nationalityInput: {
    width: "100%",
    minHeight: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#dadada",
    paddingHorizontal: 12,
    paddingRight: 32,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  nationalityText: {
    fontSize: 14,
    color: "#111",
    fontWeight: "500",
    flex: 1,
    textAlign: "center",
    textAlignVertical: "center",
    includeFontPadding: false,
  },
  dropdownIcon: {
    position: "absolute",
    right: 8,
    top: "50%",
    transform: [{ translateY: -1 }],
  },
  dropdownContainer: {
    position: "absolute",
    top: 41,
    left: 0,
    right: 0,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#dadada",
    borderRadius: 18,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    zIndex: 1000,
  },
  dropdownItem: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "#f3f4f6",
  },
  dropdownText: {
    fontSize: 14,
    color: "#374151",
    fontWeight: "400",
  },
  rowContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 16,
  },
  halfFieldGroup: {
    flex: 1,
  },
  fullNameFieldGroup: {
    flex: Platform.OS === "ios" ? 1.8 : 2,
  },
  dobFieldGroup: {
    flex: Platform.OS === "ios" ? 1.2 : 1,
  },
  halfInput: {
    width: "100%",
    minHeight: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#dadada",
    paddingHorizontal: 8,
    paddingVertical: 8,
    fontSize: 14,
    color: "#111",
    fontWeight: "500",
    includeFontPadding: false,
    textAlignVertical: "center",
  },
  guestIndex: {
    width: 20,
    textAlign: "center",
    fontWeight: "700",
    color: "#555",
    textAlignVertical: "center",
    lineHeight: 40,
  },
  spacer: { width: 8 },
  guestInput: {
    flex: 1,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#dadada",
    paddingHorizontal: 8,
    marginRight: 8,
    minWidth: 0,
    fontSize: 14,
    fontWeight: "500",
    textAlign: "left",
  },
  dobInput: {
    width: "100%",
    minWidth: 0,
    minHeight: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#dadada",
    paddingHorizontal: 12,
    flexShrink: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  dobText: {
    fontSize: 14,
    color: "#111",
    fontWeight: "600",
    letterSpacing: 0.2,
    includeFontPadding: false,
    textAlignVertical: "center",
    width: "100%",
    textAlign: "center",
  },
  iosDateOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  iosDateCard: {
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 28,
    width: "100%",
    maxWidth: 420,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 16,
    elevation: 10,
    alignItems: "center",
  },
  iosDateTitle: {
    fontSize: 22,
    fontWeight: "700",
    color: "#212529",
    marginBottom: 16,
    textAlign: "center",
    letterSpacing: 0.3,
  },
  iosDateSelected: {
    fontSize: 32,
    fontWeight: "700",
    color: "#007AFF",
    marginBottom: 24,
    textAlign: "center",
    letterSpacing: 0.5,
  },
  iosDatePickerContainer: {
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 8,
  },
  iosDatePicker: {
    width: "100%",
    alignSelf: "center",
  },
  iosDateActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 12,
    marginTop: 20,
    width: "100%",
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.4)",
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
  },
  modalCard: {
    width: "100%",
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 16,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "600",
    color: "#333",
    letterSpacing: -0.3,
    marginBottom: 8,
  },
  quickRow: { flexDirection: "row", justifyContent: "space-between" },
  quickBtn: {
    flex: 1,
    marginHorizontal: 4,
    backgroundColor: "#f3f4f6",
    borderRadius: 8,
    paddingVertical: 10,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#e5e7eb",
  },
  quickText: { color: "#111", fontWeight: "600" },
  modalActions: { flexDirection: "row", justifyContent: "flex-end", gap: 8 },
  modalButton: {
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 8,
  },
  modalButtonText: { fontWeight: "700" },

  // Total Section Styles
  totalSection: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
    marginTop: 8,
    marginBottom: 8,
  },
  totalTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: "#111",
    textAlign: "center",
    marginBottom: 16,
  },
  totalBreakdown: {
    marginBottom: 16,
  },
  totalRow: {
    flexDirection: "row",
    justifyContent: "spaceBetween" as any,
    alignItems: "center",
    marginBottom: 8,
    marginLeft: "70%",
  },
  totalLabelContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
  },
  totalLabel: {
    fontSize: 18,
    fontWeight: "700",
    color: "#007AFF",
  },
  guestLimitWarning: {
    backgroundColor: "#F8F9FA",
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    marginTop: 8,
    width: "100%",
  },
  guestLimitWarningText: {
    fontSize: 13,
    color: "#64748B",
    fontWeight: "400",
    lineHeight: 18,
    letterSpacing: -0.2,
  },
  totalCount: {
    fontSize: 16,
    color: "#666",
    fontWeight: "600",
    marginLeft: 8,
  },
  totalPrice: {
    fontSize: 24,
    fontWeight: "800",
    color: "#111",
    textAlign: "right",
  },
  // Price Card Styles (from confirm page)
  priceCard: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 16,
    marginTop: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  priceItems: {
    gap: 12,
  },
  priceItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  priceItemLeft: {
    flex: 1,
  },
  priceItemLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: "#333",
    marginBottom: 4,
  },
  priceItemUnit: {
    fontSize: 12,
    color: "#666",
  },
  priceItemValue: {
    fontSize: 16,
    fontWeight: "700",
    color: "#333",
  },
  priceDivider: {
    height: 1,
    backgroundColor: "#e0e0e0",
    marginVertical: 12,
  },
  totalValue: {
    fontSize: 22,
    fontWeight: "800",
    color: "#007AFF",
  },
  depositInfoSection: {
    backgroundColor: "#FFF9E6",
    padding: 12,
    borderRadius: 8,
    marginTop: 8,
  },
  depositInfoRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  depositInfoLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: "#FF9500",
  },
  depositInfoValue: {
    fontSize: 16,
    fontWeight: "700",
    color: "#FF9500",
  },
  depositInfoNote: {
    fontSize: 12,
    color: "#666",
    fontStyle: "italic",
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#f8f9fa",
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    color: "#666",
  },
  errorContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#f8f9fa",
    padding: 20,
  },
  errorTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#333",
    marginTop: 16,
    textAlign: "center",
  },
  retryButton: {
    marginTop: 20,
    backgroundColor: "#007AFF",
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 8,
  },
  retryButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
  },

  // Voucher & modal styles (reuse from confirm)
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  selectVoucherButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#007AFF",
    backgroundColor: "#E8F1FF",
  },
  selectVoucherButtonText: {
    color: "#007AFF",
    fontWeight: "700",
    marginRight: 6,
  },
  voucherCard: {
    backgroundColor: "#f8f9fa",
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderStyle: "solid",
    marginTop: 12,
  },
  voucherHeader: {
    flexDirection: "row",
    alignItems: "center",
  },
  voucherIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#E8F1FF",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 8,
  },
  voucherCode: {
    fontSize: 14,
    fontWeight: "700",
    color: "#007AFF",
    letterSpacing: 0.5,
    flex: 1,
  },
  voucherDetailValue: {
    fontSize: 16,
    color: "#007AFF",
    fontWeight: "700",
    marginRight: 8,
  },
  removeVoucherButton: {
    padding: 2,
    marginLeft: "auto",
  },
  voucherName: {
    fontSize: 10,
    color: "#666",
    fontWeight: "500",
    marginTop: 4,
    paddingLeft: 36,
  },
  noVoucherCard: {
    backgroundColor: "#f8f9fa",
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderStyle: "dashed",
    alignItems: "center",
    justifyContent: "center",
  },
  noVoucherText: {
    fontSize: 14,
    color: "#999",
    fontStyle: "italic",
  },
  discountLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: "#FF3B30",
  },
  discountValue: {
    fontSize: 16,
    fontWeight: "700",
    color: "#FF3B30",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.4)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    backgroundColor: "#fff",
    borderRadius: 28,
    maxHeight: "80%",
    paddingBottom: 0,
    width: "92%",
    alignSelf: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 8,
    },
    shadowOpacity: 0.08,
    shadowRadius: 24,
    elevation: 8,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 24,
    paddingBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#F5F5F5",
  },
  modalCloseButton: {
    padding: 8,
    borderRadius: 20,
    backgroundColor: "#F8F8F8",
  },
  modalScrollView: {
    paddingHorizontal: 20,
    paddingTop: 16,
  },
  voucherOptionCard: {
    backgroundColor: "#FAFAFA",
    borderRadius: 24,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1.5,
    borderColor: "#F0F0F0",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  voucherOptionCardSelected: {
    backgroundColor: "#F0F7FF",
    borderColor: "#B8D9FF",
    borderWidth: 2,
  },
  voucherOptionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  voucherOptionContent: {
    marginBottom: 12,
  },
  voucherOptionLeft: {
    flexDirection: "row",
    alignItems: "center",
  },
  radioButtonContainer: {
    marginRight: 0,
  },
  radioButton: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: "#D0D0D0",
    alignItems: "center",
    justifyContent: "center",
  },
  radioButtonSelected: {
    borderColor: "#8BC5FF",
  },
  radioButtonInner: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: "#8BC5FF",
  },
  voucherOptionIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#F0F7FF",
    alignItems: "center",
    justifyContent: "center",
  },
  voucherOptionInfo: {
    flex: 1,
  },
  voucherOptionCode: {
    fontSize: 14,
    fontWeight: "600",
    color: "#6BA3FF",
    letterSpacing: 0.3,
    flex: 1,
    marginRight: 8,
  },
  voucherOptionName: {
    fontSize: 12,
    color: "#888",
    fontWeight: "500",
    marginTop: 6,
    paddingLeft: 64,
  },
  voucherOptionDetails: {
    gap: 6,
    paddingLeft: 36,
  },
  voucherOptionDetailRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  voucherOptionDetailLabel: {
    fontSize: 13,
    color: "#666",
    fontWeight: "500",
  },
  voucherOptionDetailValue: {
    fontSize: 15,
    color: "#6BA3FF",
    fontWeight: "600",
    marginRight: 0,
  },
  voucherLoadingContainer: {
    paddingVertical: 24,
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  voucherLoadingText: {
    fontSize: 14,
    color: "#666",
  },
  voucherEmptyContainer: {
    paddingVertical: 32,
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  voucherEmptyText: {
    fontSize: 14,
    color: "#999",
    textAlign: "center",
  },
  modalFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    padding: 24,
    paddingTop: 20,
    borderTopWidth: 1,
    borderColor: "#F5F5F5",
    gap: 12,
  },
  modalCancelButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 24,
    borderWidth: 1.5,
    borderColor: "#E8E8E8",
    backgroundColor: "#FAFAFA",
    alignItems: "center",
  },
  modalCancelButtonText: {
    color: "#666",
    fontWeight: "600",
    fontSize: 15,
  },
  modalConfirmButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 24,
    backgroundColor: "#5BA3FF",
    alignItems: "center",
  },
  modalConfirmButtonDisabled: {
    backgroundColor: "#B8D9FF",
  },
  modalConfirmButtonText: {
    color: "#fff",
    fontWeight: "700",
  },
  // Warning Modal Styles - Minimal Korean Style
  warningModalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.3)",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
  },
  warningModalContent: {
    backgroundColor: "#FFFFFF",
    borderRadius: 28,
    width: "100%",
    maxWidth: 400,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#F0F0F0",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 8,
    },
    shadowOpacity: 0.08,
    shadowRadius: 32,
    elevation: 8,
  },
  warningModalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#F5F5F5",
  },
  warningModalTitle: {
    fontSize: 20,
    fontWeight: "600",
    color: "#1F2937",
    letterSpacing: -0.3,
  },
  warningModalCloseButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#F8F8F8",
    alignItems: "center",
    justifyContent: "center",
  },
  warningIconContainer: {
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 20,
    marginTop: 8,
  },
  warningModalBody: {
    padding: 24,
    paddingTop: 20,
    alignItems: "center",
  },
  warningModalMessage: {
    fontSize: 15,
    lineHeight: 22,
    color: "#64748B",
    textAlign: "center",
    fontWeight: "400",
    letterSpacing: -0.2,
  },
  warningModalFooter: {
    padding: 20,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: "#F5F5F5",
  },
  warningModalButton: {
    backgroundColor: "#3B82F6",
    paddingVertical: 14,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#3B82F6",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  warningModalButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#fff",
    letterSpacing: -0.3,
  },
});

export default styles;
