import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFF9F5",
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#FFF9F5",
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    color: "#7A8A99",
    fontWeight: "500",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: 50,
    paddingBottom: 20,
    backgroundColor: "#FFFFFF",
    borderBottomWidth: 1,
    borderBottomColor: "#F0F4F8",
  },
  headerLeft: {
    width: 80,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: "600",
    color: "#2C3E50",
    flex: 1,
    textAlign: "center",
    letterSpacing: 0.3,
  },
  purchasedButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: "#F0F4F8",
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#E8EDF2",
  },
  purchasedButtonText: {
    marginLeft: 6,
    color: "#5A6C7D",
    fontWeight: "500",
    fontSize: 12,
    letterSpacing: 0.2,
  },
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginHorizontal: 20,
    marginTop: 20,
    marginBottom: 16,
    paddingHorizontal: 20,
    paddingVertical: 10,
    backgroundColor: "#FFFFFF",
    borderRadius: 28,
    borderWidth: 1,
    borderColor: "#E8EDF2",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
    gap: 12,
  },
  searchInput: {
    flex: 1,
    fontSize: 15,
    color: "#2C3E50",
    includeFontPadding: false,
  },
  voucherHighlightSection: {
    marginHorizontal: 16,
    marginTop: 12,
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: "#e9ecef",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 3.5,
    elevation: 3,
  },
  voucherHighlightHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  voucherHighlightTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#111",
  },
  voucherHighlightAction: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  voucherHighlightActionText: {
    fontSize: 13,
    color: "#007AFF",
    fontWeight: "600",
  },
  voucherHighlightLoading: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 12,
    justifyContent: "center",
  },
  voucherHighlightLoadingText: {
    fontSize: 14,
    color: "#666",
  },
  voucherHighlightList: {
    paddingVertical: 4,
  },
  voucherHighlightCard: {
    width: 180,
    backgroundColor: "#F8FBFF",
    borderRadius: 14,
    padding: 14,
    marginRight: 12,
    borderWidth: 1,
    borderColor: "#E3F1FF",
  },
  voucherHighlightBadge: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    gap: 6,
    backgroundColor: "#007AFF",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    marginBottom: 10,
  },
  voucherHighlightBadgeText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#fff",
  },
  voucherHighlightCode: {
    fontSize: 18,
    fontWeight: "700",
    color: "#111",
    marginBottom: 6,
  },
  voucherHighlightName: {
    fontSize: 13,
    color: "#555",
    marginBottom: 12,
    minHeight: 32,
  },
  voucherHighlightFooter: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  voucherHighlightFooterText: {
    fontSize: 12,
    color: "#6c757d",
    flex: 1,
  },
  voucherHighlightEmpty: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 12,
    justifyContent: "center",
  },
  voucherHighlightEmptyText: {
    fontSize: 14,
    color: "#9aa0a6",
  },
  toursGrid: {
    padding: 20,
  },
  tourCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 28,
    marginBottom: 20,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#E8EDF2",
  },
  tourImage: {
    width: "100%",
    height: 200,
    resizeMode: "cover",
  },
  tourContent: {
    padding: 20,
  },
  tourTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#2C3E50",
    marginBottom: 12,
    lineHeight: 24,
    letterSpacing: 0.2,
  },
  tourMeta: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  locationContainer: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  locationText: {
    fontSize: 14,
    color: "#7A8A99",
    marginLeft: 6,
    flex: 1,
    fontWeight: "500",
  },
  durationContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  durationText: {
    fontSize: 14,
    color: "#7A8A99",
    marginLeft: 6,
    fontWeight: "500",
  },
  tourFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  ratingContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  ratingText: {
    fontSize: 14,
    color: "#2C3E50",
    marginLeft: 4,
    fontWeight: "600",
  },
  priceContainer: {
    flexDirection: "row",
    alignItems: "baseline",
  },
  priceText: {
    fontSize: 19,
    fontWeight: "700",
    color: "#5A6C7D",
  },
  priceUnit: {
    fontSize: 12,
    color: "#7A8A99",
    marginLeft: 4,
    fontWeight: "500",
  },
  emptyContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 60,
  },
  emptyTitle: {
    fontSize: 20,
    fontWeight: "600",
    color: "#2C3E50",
    marginTop: 16,
    marginBottom: 8,
    letterSpacing: 0.2,
  },
  emptySubtitle: {
    fontSize: 16,
    color: "#7A8A99",
    textAlign: "center",
    lineHeight: 24,
    fontWeight: "500",
  },
  bottomSpacing: {
    height: 100,
  },
  // Gift Modal Styles
  giftModalContainer: {
    position: "absolute",
    top: 170,
    left: 16,
    zIndex: 1000,
  },
  giftModalButton: {
    backgroundColor: "#FF4444",
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4.65,
    elevation: 8,
    minWidth: 140,
  },
  giftModalContent: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  giftModalTextContainer: {
    flexDirection: "column",
  },
  giftModalTextTop: {
    color: "#8B4A5A",
    fontSize: 13,
    fontWeight: "600",
    lineHeight: 16,
    letterSpacing: 0.2,
  },
  giftModalTextBottom: {
    color: "#8B4A5A",
    fontSize: 11,
    fontWeight: "500",
    lineHeight: 14,
  },
  giftModalCloseButton: {
    position: "absolute",
    top: -8,
    right: -8,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
    borderWidth: 1,
    borderColor: "#E8EDF2",
  },
  // Close Confirmation Modal Styles
  closeModalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.3)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  closeModalContent: {
    backgroundColor: "#FFFFFF",
    borderRadius: 32,
    padding: 24,
    width: "100%",
    maxWidth: 340,
    position: "relative",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 8,
    },
    shadowOpacity: 0.08,
    shadowRadius: 24,
    elevation: 8,
  },
  closeModalXButton: {
    position: "absolute",
    top: 20,
    right: 20,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#F8F9FA",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1,
    borderWidth: 1,
    borderColor: "#E8EDF2",
  },
  closeModalHeader: {
    alignItems: "center",
    marginTop: 4,
    marginBottom: 20,
  },
  closeModalTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#2C3E50",
    marginTop: 12,
    marginBottom: 6,
    textAlign: "center",
    letterSpacing: 0.2,
  },
  closeModalMessage: {
    fontSize: 13,
    color: "#7A8A99",
    textAlign: "center",
    lineHeight: 18,
    fontWeight: "500",
  },
  closeModalCheckbox: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 20,
    paddingVertical: 6,
  },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: "#D5E3ED",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  checkboxChecked: {
    backgroundColor: "#B8D4E3",
    borderColor: "#B8D4E3",
  },
  checkboxLabel: {
    fontSize: 14,
    color: "#2C3E50",
    fontWeight: "500",
    flex: 1,
  },
  closeModalSubmitButton: {
    backgroundColor: "#F5B8C4",
    borderRadius: 24,
    paddingVertical: 14,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  closeModalSubmitText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#8B4A5A",
    letterSpacing: 0.2,
  },
  // Share Tour Modal Styles (Minimal Soft Korean)
  shareModalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.4)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  shareModalContent: {
    backgroundColor: "#fff",
    borderRadius: 28,
    width: "100%",
    maxWidth: 420,
    maxHeight: "90%",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 24,
    elevation: 8,
    overflow: "hidden",
  },
  shareModalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#F5F5F5",
  },
  shareModalTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#111",
    letterSpacing: -0.3,
  },
  shareModalCloseButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#F8F8F8",
    alignItems: "center",
    justifyContent: "center",
  },
  shareModalActionButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  shareModalActionText: {
    fontSize: 15,
    fontWeight: "600",
    color: "#5BA3FF",
  },
  shareModalActionTextDisabled: {
    fontSize: 15,
    fontWeight: "600",
    color: "#D0D0D0",
  },
  shareModalBody: {
    padding: 20,
  },
  shareModalSection: {
    marginBottom: 20,
  },
  shareModalSectionTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#111",
    marginBottom: 12,
    letterSpacing: -0.2,
  },
  shareModalInputRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 8,
  },
  shareModalLabel: {
    fontSize: 14,
    color: "#999",
    marginRight: 8,
  },
  shareModalInput: {
    flex: 1,
    borderBottomWidth: 1,
    borderBottomColor: "#F0F0F0",
    paddingVertical: 10,
    paddingHorizontal: 12,
    fontSize: 14,
    color: "#111",
  },
  shareModalTextArea: {
    backgroundColor: "#FAFAFA",
    borderRadius: 20,
    padding: 16,
    minHeight: 120,
    fontSize: 14,
    color: "#111",
    textAlignVertical: "top",
    borderWidth: 1,
    borderColor: "#F0F0F0",
  },
  shareModalTourCard: {
    backgroundColor: "#FAFAFA",
    borderRadius: 24,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#F0F0F0",
  },
  shareModalTourImage: {
    width: "100%",
    height: 180,
    borderRadius: 16,
    marginBottom: 12,
  },
  shareModalTourName: {
    fontWeight: "600",
    fontSize: 16,
    color: "#111",
    marginBottom: 6,
  },
  shareModalTourDescription: {
    color: "#666",
    fontSize: 14,
    marginTop: 4,
    lineHeight: 20,
  },
  shareModalTourLink: {
    marginTop: 10,
  },
  shareModalTourLinkText: {
    color: "#5BA3FF",
    fontSize: 13,
  },
  shareModalHashtagContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  shareModalHashtagInput: {
    flex: 1,
    borderBottomWidth: 1,
    borderBottomColor: "#F0F0F0",
    paddingVertical: 10,
    paddingHorizontal: 12,
    fontSize: 14,
    color: "#999",
  },
  shareModalAddHashtagButton: {
    marginLeft: 8,
    backgroundColor: "#5BA3FF",
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 20,
  },
  shareModalAddHashtagText: {
    color: "#fff",
    fontWeight: "600",
    fontSize: 14,
  },
  shareModalHashtagList: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginBottom: 12,
  },
  shareModalHashtagTag: {
    backgroundColor: "#E8F4FF",
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    marginRight: 8,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "#D0E8FF",
  },
  shareModalHashtagText: {
    fontSize: 13,
    color: "#5BA3FF",
    fontWeight: "500",
  },
});

export default styles;
