import { StyleSheet, Platform, StatusBar } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFF9F5",
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#FFF9F5",
  },
  scrollView: {
    flex: 1,
    backgroundColor: "#FFF9F5",
  },
  scrollViewContent: {
    paddingBottom: 100,
    flexGrow: 1,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: 50,
    paddingBottom: 20,
    backgroundColor: "#FFFFFF",
    borderBottomWidth: 1,
    borderBottomColor: "#F0F4F8",
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#F8F9FA",
    alignItems: "center",
    justifyContent: "center",
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: "600",
    color: "#2C3E50",
    letterSpacing: 0.3,
  },
  headerSpacer: {
    width: 40,
  },
  content: {
    padding: 20,
  },
  card: {
    backgroundColor: "#FFFFFF",
    borderRadius: 28,
    padding: 20,
    borderWidth: 1,
    borderColor: "#E8EDF2",
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: "600",
    marginBottom: 12,
    color: "#2C3E50",
    letterSpacing: 0.2,
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  rowLast: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  label: {
    color: "#7A8A99",
    fontSize: 14,
    fontWeight: "500",
  },
  value: {
    fontWeight: "500",
    color: "#2C3E50",
    fontSize: 14,
  },
  valueBold: {
    fontWeight: "600",
    color: "#2C3E50",
    fontSize: 15,
  },
  statusSuccess: {
    fontWeight: "600",
    color: "#2e7d32",
    fontSize: 14,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "600",
    marginBottom: 12,
    color: "#2C3E50",
    letterSpacing: 0.2,
  },
  guestItem: {
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#F0F4F8",
  },
  guestName: {
    fontWeight: "500",
    color: "#2C3E50",
    fontSize: 15,
    marginBottom: 4,
  },
  guestMeta: {
    color: "#7A8A99",
    fontSize: 13,
  },
  emptyText: {
    color: "#7A8A99",
    fontSize: 14,
  },
  paymentButtonsContainer: {
    flexDirection: "row",
    gap: 12,
    marginTop: 8,
    marginBottom: 16,
  },
  continuePaymentButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#B8D4E3",
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 28,
    gap: 8,
    shadowColor: "#B8D4E3",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 3,
  },
  continuePaymentButtonText: {
    color: "#2C3E50",
    fontSize: 15,
    fontWeight: "600",
    letterSpacing: 0.2,
  },
  cancelButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F5B8C4",
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 28,
    gap: 8,
    shadowColor: "#F5B8C4",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 3,
  },
  cancelButtonText: {
    color: "#8B4A5A",
    fontSize: 15,
    fontWeight: "600",
    letterSpacing: 0.2,
  },
  actionButtonsContainer: {
    marginTop: 16,
    marginBottom: 24,
    flexDirection: "row",
    gap: 12,
  },
  confirmCompletionButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#B8D4E3",
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 28,
    gap: 8,
    shadowColor: "#B8D4E3",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 3,
  },
  confirmCompletionButtonText: {
    color: "#2C3E50",
    fontSize: 15,
    fontWeight: "600",
    letterSpacing: 0.2,
  },
  complaintButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F5B8C4",
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 28,
    gap: 8,
    shadowColor: "#F5B8C4",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 3,
  },
  complaintButtonText: {
    color: "#8B4A5A",
    fontSize: 15,
    fontWeight: "600",
    letterSpacing: 0.2,
  },
  updateInfoButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#D5E3ED",
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 28,
    marginTop: 16,
    gap: 8,
    shadowColor: "#D5E3ED",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 3,
  },
  updateInfoButtonText: {
    color: "#5A6C7D",
    fontSize: 15,
    fontWeight: "600",
    letterSpacing: 0.2,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.3)",
    justifyContent: "flex-end",
    paddingTop:
      Platform.OS === "ios" ? 50 : (StatusBar.currentHeight || 0) + 10,
    paddingHorizontal: 0,
    paddingBottom: 0,
  },
  modalContent: {
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    maxHeight: "85%",
    width: "100%",
    flexDirection: "column",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: -4,
    },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 8,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 24,
    paddingTop: 24,
    borderBottomWidth: 1,
    borderBottomColor: "#F0F4F8",
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "600",
    color: "#2C3E50",
    letterSpacing: 0.3,
  },
  modalCloseButton: {
    padding: 8,
    borderRadius: 20,
    backgroundColor: "#F8F9FA",
  },
  modalScrollView: {
    padding: 20,
    flexGrow: 0,
  },
  modalSection: {
    marginBottom: 24,
  },
  modalSectionTitle: {
    fontSize: 18,
    fontWeight: "600",
    marginBottom: 16,
    color: "#2C3E50",
    letterSpacing: 0.2,
  },
  modalField: {
    marginBottom: 16,
  },
  modalLabel: {
    fontSize: 14,
    fontWeight: "500",
    color: "#7A8A99",
    marginBottom: 8,
    letterSpacing: 0.2,
  },
  modalInput: {
    borderWidth: 1,
    borderColor: "#E8EDF2",
    borderRadius: 24,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 15,
    color: "#2C3E50",
    backgroundColor: "#F8F9FA",
  },
  modalNote: {
    marginTop: 4,
    fontSize: 12,
    color: "#7A8A99",
  },
  modalInfoBox: {
    flexDirection: "row",
    alignItems: "flex-start",
    backgroundColor: "#D5E3ED",
    padding: 12,
    borderRadius: 24,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#C4D5E3",
  },
  modalInfoText: {
    flex: 1,
    fontSize: 13,
    color: "#5A6C7D",
    marginLeft: 8,
    lineHeight: 18,
  },
  modalInputDisabled: {
    backgroundColor: "#F0F4F8",
    color: "#7A8A99",
    borderColor: "#E8EDF2",
  },
  modalTextArea: {
    height: 100,
    textAlignVertical: "top",
  },
  modalGuestCard: {
    backgroundColor: "#F8F9FA",
    borderRadius: 24,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#E8EDF2",
  },
  modalGuestTitle: {
    fontSize: 15,
    fontWeight: "600",
    color: "#2C3E50",
    marginBottom: 12,
    letterSpacing: 0.2,
  },
  modalFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    padding: 24,
    paddingBottom: Platform.OS === "ios" ? 34 : 24,
    borderTopWidth: 1,
    borderTopColor: "#F0F4F8",
    gap: 12,
  },
  modalCancelButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 24,
    backgroundColor: "#F8F9FA",
    borderWidth: 1,
    borderColor: "#E8EDF2",
    alignItems: "center",
  },
  modalCancelText: {
    fontSize: 15,
    fontWeight: "500",
    color: "#7A8A99",
  },
  modalSubmitText: {
    fontSize: 15,
    fontWeight: "600",
    color: "#2C3E50",
  },
  modalCancelButtonText: {
    fontSize: 15,
    fontWeight: "500",
    color: "#7A8A99",
  },
  modalSubmitButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 24,
    backgroundColor: "#B8D4E3",
    alignItems: "center",
  },
  modalSubmitButtonText: {
    fontSize: 15,
    fontWeight: "600",
    color: "#2C3E50",
  },
  confirmModalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.3)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  confirmModalContent: {
    backgroundColor: "#FFFFFF",
    borderRadius: 32,
    padding: 28,
    width: "100%",
    maxWidth: 400,
    alignSelf: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 8,
    },
    shadowOpacity: 0.08,
    shadowRadius: 24,
    elevation: 8,
  },
  confirmModalTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#2C3E50",
    textAlign: "center",
    marginBottom: 12,
    lineHeight: 24,
    letterSpacing: 0.2,
  },
  confirmModalMessage: {
    fontSize: 14,
    color: "#7A8A99",
    textAlign: "center",
    marginBottom: 24,
    lineHeight: 20,
  },
  confirmModalButtons: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
  },
  confirmModalCancelButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 24,
    backgroundColor: "#F8F9FA",
    borderWidth: 1,
    borderColor: "#E8EDF2",
    alignItems: "center",
  },
  confirmModalCancelText: {
    fontSize: 15,
    fontWeight: "500",
    color: "#7A8A99",
  },
  confirmModalConfirmButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 24,
    backgroundColor: "#B8D4E3",
    alignItems: "center",
  },
  confirmModalConfirmText: {
    fontSize: 15,
    fontWeight: "600",
    color: "#2C3E50",
  },
  complaintModalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.3)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  complaintModalContent: {
    backgroundColor: "#FFFFFF",
    borderRadius: 32,
    maxHeight: "80%",
    width: "100%",
    maxWidth: 500,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 8,
    },
    shadowOpacity: 0.08,
    shadowRadius: 24,
    elevation: 8,
  },
  cancelModalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.3)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  cancelModalContent: {
    backgroundColor: "#FFFFFF",
    borderRadius: 32,
    maxHeight: "80%",
    width: "100%",
    maxWidth: 420,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 8,
    },
    shadowOpacity: 0.08,
    shadowRadius: 24,
    elevation: 8,
  },
});

export default styles;
