import { StyleSheet } from "react-native";

export default StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.3)",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
  },
  modalContent: {
    backgroundColor: "#FFFFFF",
    borderRadius: 32,
    width: "100%",
    maxWidth: 500,
    maxHeight: "90%",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.1,
    shadowRadius: 16,
    elevation: 8,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 20,
    borderBottomWidth: 0,
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: "600",
    color: "#2D2D2D",
    letterSpacing: -0.5,
  },
  closeButton: {
    padding: 8,
    borderRadius: 24,
    backgroundColor: "#FFF9F5",
  },
  modalScrollView: {
    flexGrow: 1,
    maxHeight: "60%",
  },
  form: {
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 16,
  },
  field: {
    marginBottom: 24,
  },
  label: {
    fontSize: 15,
    fontWeight: "600",
    color: "#2D2D2D",
    marginBottom: 12,
    letterSpacing: -0.3,
  },
  input: {
    backgroundColor: "#FFF9F5",
    borderRadius: 24,
    borderWidth: 0,
    paddingHorizontal: 20,
    paddingVertical: 16,
    fontSize: 16,
    color: "#2D2D2D",
    letterSpacing: -0.3,
  },
  textArea: {
    minHeight: 140,
    maxHeight: 220,
    textAlignVertical: "top",
  },
  characterCount: {
    fontSize: 13,
    color: "#B8B8B8",
    textAlign: "right",
    marginTop: 8,
    letterSpacing: -0.2,
  },
  optionalText: {
    fontSize: 13,
    fontWeight: "400",
    color: "#B8B8B8",
    letterSpacing: -0.2,
  },
  reasonContainer: {
    gap: 14,
  },
  reasonButton: {
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderRadius: 24,
    backgroundColor: "#FFF9F5",
    borderWidth: 0,
  },
  reasonButtonActive: {
    backgroundColor: "#E8F5E9",
    borderWidth: 0,
  },
  reasonButtonContent: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
  },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: "#E0E0E0",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFFFF",
  },
  checkboxActive: {
    backgroundColor: "#B5EAD7",
    borderColor: "#B5EAD7",
  },
  reasonButtonText: {
    fontSize: 15,
    color: "#8E8E93",
    fontWeight: "500",
    flex: 1,
    letterSpacing: -0.3,
  },
  reasonButtonTextActive: {
    color: "#81C784",
    fontWeight: "600",
  },
  modalFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 24,
    paddingVertical: 20,
    borderTopWidth: 0,
    gap: 14,
  },
  cancelButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 28,
    backgroundColor: "#FFF9F5",
    alignItems: "center",
  },
  cancelButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#8E8E93",
    letterSpacing: -0.3,
  },
  submitButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 28,
    backgroundColor: "#B5EAD7",
    alignItems: "center",
  },
  submitButtonDisabled: {
    backgroundColor: "#F5F5F5",
  },
  submitButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#FFFFFF",
    letterSpacing: -0.3,
  },
});

