import { StyleSheet } from "react-native";
import { colors } from "../../constants/theme";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  containerIos: {
    paddingTop: 40,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 12,
    paddingTop: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#E5E5E5",
    backgroundColor: "#FFFFFF",
  },
  backButton: {
    padding: 8,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#212529",
    flex: 1,
    textAlign: "center",
  },
  headerRight: {
    width: 40,
  },
  scrollView: {
    flex: 1,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 40,
  },
  loadingText: {
    marginTop: 12,
    fontSize: 16,
    color: colors.text.secondary,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 60,
    paddingHorizontal: 32,
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#212529",
    marginTop: 16,
    marginBottom: 8,
  },
  emptyDescription: {
    fontSize: 14,
    color: colors.text.secondary,
    textAlign: "center",
    lineHeight: 20,
  },
  articlesList: {
    padding: 16,
    paddingBottom: 20,
  },
  articleCardWrapper: {
    marginBottom: 16,
  },
  articleCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    marginHorizontal: 0,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    overflow: "hidden",
  },
  articleImageContainer: {
    height: 180,
    backgroundColor: "#F5F5F5",
    overflow: "hidden",
  },
  articleImage: {
    width: "100%",
    height: "100%",
  },
  articleContent: {
    padding: 16,
  },
  articleTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#212529",
    marginBottom: 8,
    lineHeight: 22,
  },
  articleSummary: {
    fontSize: 14,
    color: colors.text.secondary,
    lineHeight: 20,
    marginBottom: 12,
  },
  articleMeta: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 8,
  },
  articleAuthor: {
    flexDirection: "row",
    alignItems: "center",
  },
  articleAuthorText: {
    fontSize: 12,
    color: colors.text.secondary,
    marginLeft: 4,
  },
  articleDate: {
    fontSize: 12,
    color: colors.text.secondary,
  },
  articleMetaRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  articleCommentCount: {
    fontSize: 12,
    color: colors.text.secondary,
  },
  articleTags: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 8,
  },
  articleTag: {
    fontSize: 12,
    color: "#007AFF",
    backgroundColor: "#F0F8FF",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    marginRight: 8,
    marginBottom: 4,
  },
  searchContainer: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 8,
    backgroundColor: "#FFFFFF",
  },
  searchInputContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F5F5F5",
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: "#E5E5E5",
  },
  searchIcon: {
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
    color: "#212529",
    paddingVertical: 0,
  },
  clearSearchButton: {
    marginLeft: 8,
    padding: 4,
  },
  articleCommentsPreview: {
    backgroundColor: "#FFFFFF",
    marginHorizontal: 0,
    marginTop: 8,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingTop: 12,
    paddingBottom: 8,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    borderWidth: 1,
    borderColor: "#F0F0F0",
  },
  commentPreviewItem: {
    flexDirection: "row",
    marginBottom: 12,
  },
  commentPreviewAvatar: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "#E5E5E5",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 8,
    marginTop: 2,
    overflow: "hidden",
  },
  commentPreviewAvatarImage: {
    width: 24,
    height: 24,
    borderRadius: 12,
  },
  commentPreviewContent: {
    flex: 1,
  },
  commentPreviewUserName: {
    fontSize: 13,
    fontWeight: "600",
    color: "#212529",
    marginBottom: 2,
  },
  commentPreviewText: {
    fontSize: 13,
    color: "#495057",
    lineHeight: 18,
    marginBottom: 4,
  },
  commentPreviewDate: {
    fontSize: 11,
    color: colors.text.secondary,
  },
  viewAllCommentsButton: {
    marginTop: 4,
    paddingVertical: 8,
  },
  viewAllCommentsText: {
    fontSize: 13,
    color: "#007AFF",
    fontWeight: "500",
  },
});
